BLS - Cleaning Data

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

In [10]:
file_path = Path("../data/raw/BLS/BLS_2025(OES Sheet).csv")
df = pd.read_csv(file_path, header=2)

np.shape(df)

(453, 18)

In [11]:
print(df.columns)

Index(['Area', 'Industry', 'Occupation', 'Employment (1)',
       'Employment percent relative standard error (3)', 'Hourly mean wage',
       'Annual mean wage (2)', 'Wage percent relative standard error (3)',
       'Hourly 10th percentile wage', 'Hourly 25th percentile wage',
       'Hourly median wage', 'Hourly 75th percentile wage',
       'Hourly 90th percentile wage', 'Annual 10th percentile wage (2)',
       'Annual 25th percentile wage (2)', 'Annual median wage (2)',
       'Annual 75th percentile wage (2)', 'Annual 90th percentile wage (2)'],
      dtype='str')

In [12]:
df.columns = (df.columns.str.strip().str.lower().str.replace(r"\(\d+\)", "", regex=True).str.replace("%", "percent", regex=False).str.replace(r"[^a-z0-9]+", "_", regex=True).str.strip("_"))

df.columns.tolist()

['area',
 'industry',
 'occupation',
 'employment',
 'employment_percent_relative_standard_error',
 'hourly_mean_wage',
 'annual_mean_wage',
 'wage_percent_relative_standard_error',
 'hourly_10th_percentile_wage',
 'hourly_25th_percentile_wage',
 'hourly_median_wage',
 'hourly_75th_percentile_wage',
 'hourly_90th_percentile_wage',
 'annual_10th_percentile_wage',
 'annual_25th_percentile_wage',
 'annual_median_wage',
 'annual_75th_percentile_wage',
 'annual_90th_percentile_wage']

In [14]:
numeric_columns = [
    "employment",
    "employment_percent_relative_standard_error",
    "hourly_mean_wage",
    "annual_mean_wage",
    "wage_percent_relative_standard_error",
    "hourly_10th_percentile_wage",
    "hourly_25th_percentile_wage",
    "hourly_median_wage",
    "hourly_75th_percentile_wage",
    "hourly_90th_percentile_wage",
    "annual_10th_percentile_wage",
    "annual_25th_percentile_wage",
    "annual_median_wage",
    "annual_75th_percentile_wage",
    "annual_90th_percentile_wage"
]

In [15]:
for col in numeric_columns:
    df[col] = (df[col].astype(str).str.replace("$", "", regex=False).str.replace(",", "", regex=False).str.strip())

    df[col] = pd.to_numeric(df[col], errors="coerce")

In [17]:
missing = pd.DataFrame({"missing_count": df.isna().sum()})

missing.sort_values("missing_count", ascending=False)

                                            missing_count
hourly_25th_percentile_wage                             9
industry                                                9
annual_75th_percentile_wage                             9
annual_median_wage                                      9
annual_25th_percentile_wage                             9
annual_10th_percentile_wage                             9
hourly_90th_percentile_wage                             9
hourly_75th_percentile_wage                             9
hourly_median_wage                                      9
annual_90th_percentile_wage                             9
hourly_10th_percentile_wage                             9
wage_percent_relative_standard_error                    9
annual_mean_wage                                        9
hourly_mean_wage                                        9
employment_percent_relative_standard_error              9
employment                                              9
occupation                                              9
area                                                    3

In [18]:
missing_rows = df[df.isna().any(axis=1)]

missing_rows

,area,industry,occupation,employment,employment_percent_relative_standard_error,hourly_mean_wage,annual_mean_wage,wage_percent_relative_standard_error,hourly_10th_percentile_wage,hourly_25th_percentile_wage,hourly_median_wage,hourly_75th_percentile_wage,hourly_90th_percentile_wage,annual_10th_percentile_wage,annual_25th_percentile_wage,annual_median_wage,annual_75th_percentile_wage,annual_90th_percentile_wage
444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
445,Footnotes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446,(1) Estimates for detailed occupations do not ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
447,(2) Annual wages have been calculated by multi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
448,(3) The relative standard error (RSE) is a mea...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
450,SOC code: Standard Occupational Classification...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
451,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
452,"Data extracted on September 16, 2026",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df.dtypes

area                                              str
industry                                          str
occupation                                        str
employment                                    float64
employment_percent_relative_standard_error    float64
hourly_mean_wage                              float64
annual_mean_wage                              float64
wage_percent_relative_standard_error          float64
hourly_10th_percentile_wage                   float64
hourly_25th_percentile_wage                   float64
hourly_median_wage                            float64
hourly_75th_percentile_wage                   float64
hourly_90th_percentile_wage                   float64
annual_10th_percentile_wage                   float64
annual_25th_percentile_wage                   float64
annual_median_wage                            float64
annual_75th_percentile_wage                   float64
annual_90th_percentile_wage                   float64
dtype: object

In [20]:
df = df.iloc[:444].copy()

df.shape

(444, 18)

In [21]:
df.reset_index(drop=True, inplace=True)

In [22]:
df.isna().sum()

area                                          0
industry                                      0
occupation                                    0
employment                                    0
employment_percent_relative_standard_error    0
hourly_mean_wage                              0
annual_mean_wage                              0
wage_percent_relative_standard_error          0
hourly_10th_percentile_wage                   0
hourly_25th_percentile_wage                   0
hourly_median_wage                            0
hourly_75th_percentile_wage                   0
hourly_90th_percentile_wage                   0
annual_10th_percentile_wage                   0
annual_25th_percentile_wage                   0
annual_median_wage                            0
annual_75th_percentile_wage                   0
annual_90th_percentile_wage                   0
dtype: int64

In [23]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [24]:
df[numeric_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
employment,444.0,1.940913e+06,1.002163e+07,1000.00,110692.500,343980.000,1.040198e+06,1.554957e+08
employment_percent_relative_standard_error,444.0,1.509009e-02,4.325619e-02,0.00,0.000,0.000,0.000000e+00,4.000000e-01
hourly_mean_wage,444.0,3.466725e+01,1.127402e+01,16.73,26.520,32.800,4.130750e+01,7.517000e+01
annual_mean_wage,444.0,7.210727e+04,2.345022e+04,34790.00,55160.000,68225.000,8.592500e+04,1.563500e+05
wage_percent_relative_standard_error,444.0,7.840090e-01,7.657695e-01,0.00,0.400,0.600,9.000000e-01,6.000000e+00
hourly_10th_percentile_wage,444.0,1.762200e+01,3.721785e+00,10.21,15.000,17.380,1.867500e+01,3.437000e+01
hourly_25th_percentile_wage,444.0,2.174998e+01,5.702888e+00,13.00,17.625,21.400,2.329250e+01,4.797000e+01
hourly_median_wage,444.0,2.889153e+01,9.938695e+00,15.49,21.930,27.595,3.321000e+01,7.935000e+01
hourly_75th_percentile_wage,444.0,4.040221e+01,1.537844e+01,17.73,29.080,37.695,4.904500e+01,1.034400e+02
hourly_90th_percentile_wage,444.0,5.768547e+01,2.235890e+01,22.24,39.975,52.550,7.043250e+01,1.481200e+02
annual_10th_percentile_wage,444.0,3.665214e+04,7.741702e+03,21240.00,31200.000,36145.000,3.884250e+04,7.150000e+04
annual_25th_percentile_wage,444.0,4.523890e+04,1.186210e+04,27040.00,36657.500,44505.000,4.844250e+04,9.977000e+04
annual_median_wage,444.0,6.009354e+04,2.067254e+04,32220.00,45607.500,57400.000,6.907250e+04,1.650400e+05
annual_75th_percentile_wage,444.0,8.403570e+04,3.198738e+04,36870.00,60490.000,78405.000,1.020075e+05,2.151600e+05
annual_90th_percentile_wage,444.0,1.199846e+05,4.650687e+04,46250.00,83147.500,109295.000,1.464925e+05,3.080900e+05

In [25]:
skewness = df[numeric_columns].skew().sort_values(ascending=False)

skewness

employment                                    13.285974
employment_percent_relative_standard_error     3.640729
wage_percent_relative_standard_error           3.136890
hourly_25th_percentile_wage                    1.496684
annual_25th_percentile_wage                    1.496680
hourly_median_wage                             1.492183
annual_median_wage                             1.492004
annual_10th_percentile_wage                    1.418976
hourly_10th_percentile_wage                    1.418501
annual_75th_percentile_wage                    1.062031
hourly_75th_percentile_wage                    1.061967
hourly_mean_wage                               0.931858
annual_mean_wage                               0.931837
annual_90th_percentile_wage                    0.909680
hourly_90th_percentile_wage                    0.909652
dtype: float64

In [26]:
outlier_summary = []

for col in numeric_columns:
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]

    outlier_summary.append({"feature": col, "outliers": len(outliers), "percent": round(len(outliers) / len(df) * 100, 2)})

outlier_summary = pd.DataFrame(outlier_summary)

outlier_summary

                                       feature  outliers  percent
0                                   employment        58    13.06
1   employment_percent_relative_standard_error        57    12.84
2                             hourly_mean_wage         9     2.03
3                             annual_mean_wage         9     2.03
4         wage_percent_relative_standard_error        46    10.36
5                  hourly_10th_percentile_wage        26     5.86
6                  hourly_25th_percentile_wage        28     6.31
7                           hourly_median_wage        17     3.83
8                  hourly_75th_percentile_wage        14     3.15
9                  hourly_90th_percentile_wage         5     1.13
10                 annual_10th_percentile_wage        26     5.86
11                 annual_25th_percentile_wage        28     6.31
12                          annual_median_wage        17     3.83
13                 annual_75th_percentile_wage        14     3.15
14                 annual_90th_percentile_wage         5     1.13

In [27]:
hourly_columns = ["hourly_mean_wage", "hourly_10th_percentile_wage", "hourly_25th_percentile_wage", "hourly_median_wage", "hourly_75th_percentile_wage", "hourly_90th_percentile_wage"]

df = df.drop(columns=hourly_columns)

print(df.shape)
df.columns.tolist()

(444, 12)

['area',
 'industry',
 'occupation',
 'employment',
 'employment_percent_relative_standard_error',
 'annual_mean_wage',
 'wage_percent_relative_standard_error',
 'annual_10th_percentile_wage',
 'annual_25th_percentile_wage',
 'annual_median_wage',
 'annual_75th_percentile_wage',
 'annual_90th_percentile_wage']

In [28]:
df["log_employment"] = np.log1p(df["employment"])

print("Original employment skewness:", df["employment"].skew())
print("Log employment skewness:", df["log_employment"].skew())

Original employment skewness: 13.285974270323122
Log employment skewness: 0.024308815358638707

In [29]:
wage_columns = [
    "annual_mean_wage",
    "annual_10th_percentile_wage",
    "annual_25th_percentile_wage",
    "annual_median_wage",
    "annual_75th_percentile_wage",
    "annual_90th_percentile_wage"
]

for col in wage_columns:
    lower = df[col].quantile(0.01)
    upper = df[col].quantile(0.99)

    df[f"{col}_winsorized"] = df[col].clip(
        lower=lower,
        upper=upper
    )

In [30]:
df["wage_spread"] = (
    df["annual_90th_percentile_wage"]
    - df["annual_10th_percentile_wage"]
)

df["wage_progression_ratio"] = (
    df["annual_90th_percentile_wage"]
    / df["annual_10th_percentile_wage"]
)

In [32]:
df[["employment", "log_employment", "annual_median_wage", "annual_median_wage_winsorized", "wage_spread", "wage_progression_ratio"]].describe().T

,count,mean,std,min,25%,50%,75%,max
employment,444.0,1.940913e+06,1.002163e+07,1000.000000,110692.500000,343980.000000,1.040198e+06,1.554957e+08
log_employment,444.0,1.271092e+01,1.801550e+00,6.908755,11.614427,12.748339,1.385492e+01,1.886213e+01
annual_median_wage,444.0,6.009354e+04,2.067254e+04,32220.000000,45607.500000,57400.000000,6.907250e+04,1.650400e+05
annual_median_wage_winsorized,444.0,5.993316e+04,1.991960e+04,34938.600000,45607.500000,57400.000000,6.907250e+04,1.296098e+05
wage_spread,444.0,8.333250e+04,4.181328e+04,19950.000000,50972.500000,71505.000000,1.028325e+05,2.576100e+05
wage_progression_ratio,444.0,3.230633e+00,9.333984e-01,1.581945,2.546414,3.064279,3.703958e+00,6.657479e+00

In [33]:
df[["employment", "log_employment", "annual_median_wage", "annual_median_wage_winsorized", "wage_spread", "wage_progression_ratio"]].skew()

employment                       13.285974
log_employment                    0.024309
annual_median_wage                1.492004
annual_median_wage_winsorized     1.198668
wage_spread                       1.044724
wage_progression_ratio            1.022947
dtype: float64

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 444 entries, 0 to 443
Data columns (total 21 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   area                                        444 non-null    str
 1   industry                                    444 non-null    str
 2   occupation                                  444 non-null    str
 3   employment                                  444 non-null    float64
 4   employment_percent_relative_standard_error  444 non-null    float64
 5   annual_mean_wage                            444 non-null    float64
 6   wage_percent_relative_standard_error        444 non-null    float64
 7   annual_10th_percentile_wage                 444 non-null    float64
 8   annual_25th_percentile_wage                 444 non-null    float64
 9   annual_median_wage                          444 non-null    float64
 10  annual_75th_percentile_wage                 444 non-null    float64
 11  annual_90th_percentile_wage                 444 non-null    float64
 12  log_employment                              444 non-null    float64
 13  annual_mean_wage_winsorized                 444 non-null    float64
 14  annual_10th_percentile_wage_winsorized      444 non-null    float64
 15  annual_25th_percentile_wage_winsorized      444 non-null    float64
 16  annual_median_wage_winsorized               444 non-null    float64
 17  annual_75th_percentile_wage_winsorized      444 non-null    float64
 18  annual_90th_percentile_wage_winsorized      444 non-null    float64
 19  wage_spread                                 444 non-null    float64
 20  wage_progression_ratio                      444 non-null    float64
dtypes: float64(18), str(3)
memory usage: 73.0 KB

In [35]:
df.head()

,area,industry,occupation,employment,employment_percent_relative_standard_error,annual_mean_wage,wage_percent_relative_standard_error,annual_10th_percentile_wage,annual_25th_percentile_wage,annual_median_wage,...,annual_90th_percentile_wage,log_employment,annual_mean_wage_winsorized,annual_10th_percentile_wage_winsorized,annual_25th_percentile_wage_winsorized,annual_median_wage_winsorized,annual_75th_percentile_wage_winsorized,annual_90th_percentile_wage_winsorized,wage_spread,wage_progression_ratio
0,National,"Cross-Industry, Private, Federal, State, and L...",All Occupations (00-0000),155495730.0,0.0,69770.0,0.1,31200.0,37590.0,50980.0,...,128560.0,18.862129,69770.0,31200.0,37590.0,50980.0,80520.0,128560.0,97360.0,4.120513
1,National,"Cross-industry, Private Ownership only (000001)",All Occupations (00-0000),132782040.0,0.0,68930.0,0.1,30670.0,37030.0,48990.0,...,129020.0,18.704220,68930.0,30670.0,37030.0,48990.0,79110.0,129020.0,98350.0,4.206717
2,National,"Sector 11 - Agriculture, Forestry, Fishing and...",All Occupations (00-0000),413350.0,0.0,44590.0,0.4,33880.0,34630.0,36740.0,...,63350.0,12.932052,44590.0,33880.0,34630.0,36740.0,46420.0,63350.0,29470.0,1.869835
3,National,Forestry and Logging (113000),All Occupations (00-0000),41620.0,0.1,56690.0,0.8,34670.0,44290.0,52640.0,...,79040.0,10.636360,56690.0,34670.0,44290.0,52640.0,63850.0,79040.0,44370.0,2.279781
4,National,Logging (113300),All Occupations (00-0000),41620.0,0.1,56690.0,0.8,34670.0,44290.0,52640.0,...,79040.0,10.636360,56690.0,34670.0,44290.0,52640.0,63850.0,79040.0,44370.0,2.279781

In [36]:
df["year"] = 2025

In [43]:
output_path = Path("../data/processed/BLS_2025_cleaned.csv")

output_path.parent.mkdir(parents=True, exist_ok=True)

df.to_csv(output_path, index=False)

print(f"Saved cleaned dataset to: {output_path}")
print("Final shape:", df.shape)

Saved cleaned dataset to: ../data/processed/BLS_2025_cleaned.csv
Final shape: (444, 31)

In [44]:
df_check = pd.read_csv(output_path)

print(df_check.shape)
print("Missing values:", df_check.isna().sum().sum())
print("Duplicates:", df_check.duplicated().sum())

df_check.head()

(444, 31)
Missing values: 0
Duplicates: 0

,area,industry,occupation,employment,employment_percent_relative_standard_error,annual_mean_wage,wage_percent_relative_standard_error,annual_10th_percentile_wage,annual_25th_percentile_wage,annual_median_wage,...,year,log_employment_normalized,annual_mean_wage_winsorized_normalized,annual_10th_percentile_wage_winsorized_normalized,annual_25th_percentile_wage_winsorized_normalized,annual_median_wage_winsorized_normalized,annual_75th_percentile_wage_winsorized_normalized,annual_90th_percentile_wage_winsorized_normalized,wage_spread_normalized,wage_progression_ratio_normalized
0,National,"Cross-Industry, Private, Federal, State, and L...",All Occupations (00-0000),155495730.0,0.0,69770.0,0.1,31200.0,37590.0,50980.0,...,2025,3.418252,-0.098478,-0.715940,-0.662300,-0.449972,-0.107018,0.197986,0.335858,0.954452
1,National,"Cross-industry, Private Ownership only (000001)",All Occupations (00-0000),132782040.0,0.0,68930.0,0.1,30670.0,37030.0,48990.0,...,2025,3.330502,-0.134758,-0.785912,-0.711566,-0.549986,-0.152217,0.208182,0.359561,1.046911
2,National,"Sector 11 - Agriculture, Forestry, Fishing and...",All Occupations (00-0000),413350.0,0.0,44590.0,0.4,33880.0,34630.0,36740.0,...,2025,0.122886,-1.186019,-0.362119,-0.922709,-1.165652,-1.200141,-1.247381,-1.289620,-1.459540
3,National,Forestry and Logging (113000),All Occupations (00-0000),41620.0,0.1,56690.0,0.8,34670.0,44290.0,52640.0,...,2025,-1.152839,-0.663412,-0.257821,-0.072860,-0.366543,-0.641398,-0.899615,-0.932872,-1.019848
4,National,Logging (113300),All Occupations (00-0000),41620.0,0.1,56690.0,0.8,34670.0,44290.0,52640.0,...,2025,-1.152839,-0.663412,-0.257821,-0.072860,-0.366543,-0.641398,-0.899615,-0.932872,-1.019848

In [41]:
import sklearn
from sklearn.preprocessing import StandardScaler

features_to_normalize = [
    "log_employment",
    "annual_mean_wage_winsorized",
    "annual_10th_percentile_wage_winsorized",
    "annual_25th_percentile_wage_winsorized",
    "annual_median_wage_winsorized",
    "annual_75th_percentile_wage_winsorized",
    "annual_90th_percentile_wage_winsorized",
    "wage_spread",
    "wage_progression_ratio"
]

scaler = StandardScaler()

df[[f"{col}_normalized" for col in features_to_normalize]] = (
    scaler.fit_transform(df[features_to_normalize])
)

In [42]:
df[[f"{col}_normalized" for col in features_to_normalize]].describe().T

,count,mean,std,min,25%,50%,75%,max
log_employment_normalized,444.0,-1.920386e-16,1.001128,-3.224283,-0.609323,0.020796,0.635728,3.418252
annual_mean_wage_winsorized_normalized,444.0,-1.840370e-16,1.001128,-1.471199,-0.729494,-0.165207,0.599268,3.086010
annual_10th_percentile_wage_winsorized_normalized,444.0,4.400884e-16,1.001128,-1.794698,-0.715940,-0.063088,0.293044,3.721674
annual_25th_percentile_wage_winsorized_normalized,444.0,2.160434e-16,1.001128,-1.449421,-0.744337,-0.053945,0.292461,3.272993
annual_median_wage_winsorized_normalized,444.0,1.040209e-16,1.001128,-1.256188,-0.719985,-0.127313,0.459329,3.501840
annual_75th_percentile_wage_winsorized_normalized,444.0,-1.920386e-16,1.001128,-1.369690,-0.749107,-0.174817,0.581794,2.863815
annual_90th_percentile_wage_winsorized_normalized,444.0,-1.120225e-16,1.001128,-1.471398,-0.808573,-0.229019,0.595456,2.750116
wage_spread_normalized,444.0,-3.200643e-17,1.001128,-1.517556,-0.774790,-0.283184,0.466885,4.172696
wage_progression_ratio_normalized,444.0,4.000804e-16,1.001128,-1.768320,-0.733867,-0.178425,0.507671,3.675507